---
# dependencies: banzai vault operator
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault-crow-example
  labels:
    app.kubernetes.io/name: crow
    app.kubernetes.io/instance: crow-example
spec:
  size: 1
  image: vault:1.10.4

  # Set use which node label for pod anti-affinity. Prevent all vault put on same node.
  podAntiAffinity: kubernetes.io/hostname

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: vault-crow-example-sa

  # A YAML representation of a final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
      raft:
        path: /vault/file
        # recomended for production: 1
        performance_multiplier: 1
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    disable_mlock: true
    telemetry:
      statsd_address: localhost:9125
    api_addr: https://vault.vault-server:8200
    cluster_addr: "https://${.Env.POD_NAME}:8201"
    ui: true
  vaultEnvsConfig:
    - name: VAULT_LOG_LEVEL
      # note: disable debug log level on production
      # Supported values (in order of detail) are "trace", "debug", "info", "warn", and "err"
      value: info

  serviceRegistrationEnabled: true

  resources:
    # A YAML representation of resource ResourceRequirements for vault container
    # Detail can reference: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container
    vault:
      limits:
        memory: "128Mi"
        cpu: "100m"
      requests:
        memory: "128Mi"
        cpu: "20m"

  volumeMounts:
    - name: vault-raft
      mountPath: /vault/file

  # Use local disk to store Vault file data, see config section.
  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
