name: Publish

on:
  workflow_run:
    workflows: ["Docker Image"]
    types:
      - completed
    branches:
      - 'master'

env:
  DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKER_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: push
      run: |
        make image-push
