name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Tests
      run: make test

    - name: Build the Docker image
      run: make image-build
